# Generated by Django 5.0 on 2024-09-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HirePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('expart_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('offered_money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
