# Generated by Django 5.0 on 2024-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_hirepost_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
