# Generated by Django 5.0 on 2024-09-29 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
