# Generated by Django 5.0 on 2024-09-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_professional_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
