# Generated by Django 5.1.1 on 2024-10-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0005_alter_professional_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirepost",
            name="hireID",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
