# Generated by Django 5.1.1 on 2024-10-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0006_hirepost_hireid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirepost",
            name="id",
        ),
        migrations.AlterField(
            model_name="hirepost",
            name="hireID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
