# Generated by Django 5.1.1 on 2024-10-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0007_remove_hirepost_id_alter_hirepost_hireid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="id",
        ),
        migrations.AddField(
            model_name="professional",
            name="ProfessionID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="bidForJob",
            fields=[
                ("jobID", models.AutoField(primary_key=True, serialize=False)),
                ("bidPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offer", models.TextField()),
                (
                    "pID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bidPid",
                        to="hire.professional",
                    ),
                ),
            ],
        ),
    ]
