# Generated by Django 5.1.1 on 2024-10-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0008_remove_professional_id_professional_professionid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidforjob",
            name="pID",
        ),
    ]
