# Generated by Django 5.1.1 on 2024-10-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0009_remove_bidforjob_pid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="bidForJob",
        ),
    ]
