# Generated by Django 5.1.1 on 2024-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0010_delete_bidforjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="BidForJob",
            fields=[
                ("jobID", models.AutoField(primary_key=True, serialize=False)),
                ("bidPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("offer", models.TextField()),
            ],
        ),
    ]
