# Generated by Django 5.1.1 on 2024-10-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0011_bidforjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidforjob",
            name="jobID",
        ),
        migrations.AddField(
            model_name="bidforjob",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
