# Generated by Django 5.1.1 on 2024-10-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0012_remove_bidforjob_jobid_bidforjob_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidforjob",
            name="jobID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job",
                to="hire.hirepost",
            ),
            preserve_default=False,
        ),
    ]
