# Generated by Django 5.1.1 on 2024-10-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0013_bidforjob_jobid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidforjob",
            name="id",
        ),
        migrations.AddField(
            model_name="bidforjob",
            name="bID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bidforjob",
            name="pID",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidPid",
                to="hire.professional",
            ),
            preserve_default=False,
        ),
    ]
