# Generated by Django 5.1.1 on 2024-10-05 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hire", "0014_remove_bidforjob_id_bidforjob_bid_bidforjob_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidforjob",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
